<a href="https://colab.research.google.com/github/jessica8403/TIL/blob/master/pandas_practice_12_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [158]:
import numpy as np


In [159]:
arr1d=np.array([1,2,3,4,5])

In [160]:
arr1d

array([1, 2, 3, 4, 5])

In [161]:
arr1d.shape


(5,)

In [162]:
arrN = np.arange(1,31).reshape(3,10)
arrN

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [163]:
arrN= np.arange(1, 51).reshape(5, 10)

In [164]:
arrN


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [165]:
np.random.randint(1,46,size=6)

array([16,  7, 35, 34, 35, 40])

In [166]:
arr = np.arange(1, 46)
np.random.choice(arr, size=6, replace=False)

array([13,  9, 27, 25,  4, 30])

In [167]:
import pandas as pd

In [168]:
series=pd.Series([1,2,3,4,5,6])

In [169]:
series

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [170]:
weight = pd.DataFrame([
  [76.4, 'kg'],
  [75.7, 'kg'],
  [76, 'kg'],
  [76.2, 'kg']
])

In [171]:
weight

0   1
0  76.4  kg
1  75.7  kg
2  76.0  kg
3  76.2  kg

In [172]:
weight= pd.DataFrame ([
                       [ 55, 'kg'],
                      [67,'kg'],
                      [98, 'kg']
                       ])

In [173]:
weight


0   1
0  55  kg
1  67  kg
2  98  kg

In [174]:
rawData=pd.read_csv('/content/drive/MyDrive/weight_log.csv의 사본 (1)')

In [175]:
rawData

회차   이름         측정일   몸무게  단위   담당   지점
0   1  홍길동  2020-03-01  76.4  kg  박현경  관악구
1   2  홍길동  2020-03-02  75.7  kg  김현경  관악구
2   3  홍길동  2020-03-03  76.0  kg  최현경  여의도
3   4  홍길동  2020-03-04   NaN  kg  최현경  여의도
4   5  홍길동  2020-03-05  76.2  kg  김현경  강남구
5   6  홍길동  2020-03-06  75.7  kg  최현경  서초구
6   7  홍길동  2020-03-07   NaN  kg  최현경  서초구
7   8  홍길동  2020-03-08   NaN  kg  김현경  서초구
8   9  홍길동  2020-03-09  75.0  kg  김현경  서초구

In [176]:
rawData.head(n=5)

회차   이름         측정일   몸무게  단위   담당   지점
0   1  홍길동  2020-03-01  76.4  kg  박현경  관악구
1   2  홍길동  2020-03-02  75.7  kg  김현경  관악구
2   3  홍길동  2020-03-03  76.0  kg  최현경  여의도
3   4  홍길동  2020-03-04   NaN  kg  최현경  여의도
4   5  홍길동  2020-03-05  76.2  kg  김현경  강남구

In [177]:
rawData.tail(n=4)

회차   이름         측정일   몸무게  단위   담당   지점
5   6  홍길동  2020-03-06  75.7  kg  최현경  서초구
6   7  홍길동  2020-03-07   NaN  kg  최현경  서초구
7   8  홍길동  2020-03-08   NaN  kg  김현경  서초구
8   9  홍길동  2020-03-09  75.0  kg  김현경  서초구

In [178]:
rawData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   회차      9 non-null      int64  
 1   이름      9 non-null      object 
 2   측정일     9 non-null      object 
 3   몸무게     6 non-null      float64
 4   단위      9 non-null      object 
 5   담당      9 non-null      object 
 6   지점      9 non-null      object 
dtypes: float64(1), int64(1), object(5)
memory usage: 632.0+ bytes


In [179]:
rawData.describe(include='all')

회차   이름         측정일        몸무게   단위   담당   지점
count   9.000000    9           9   6.000000    9    9    9
unique       NaN    1           9        NaN    1    3    4
top          NaN  홍길동  2020-03-03        NaN   kg  최현경  서초구
freq         NaN    9           1        NaN    9    4    4
mean    5.000000  NaN         NaN  75.833333  NaN  NaN  NaN
std     2.738613  NaN         NaN   0.492612  NaN  NaN  NaN
min     1.000000  NaN         NaN  75.000000  NaN  NaN  NaN
25%     3.000000  NaN         NaN  75.700000  NaN  NaN  NaN
50%     5.000000  NaN         NaN  75.850000  NaN  NaN  NaN
75%     7.000000  NaN         NaN  76.150000  NaN  NaN  NaN
max     9.000000  NaN         NaN  76.400000  NaN  NaN  NaN

In [180]:
rawData['몸무게']

0    76.4
1    75.7
2    76.0
3     NaN
4    76.2
5    75.7
6     NaN
7     NaN
8    75.0
Name: 몸무게, dtype: float64

In [181]:
col=['이름','몸무게','담당']

In [182]:
rawData[col]

이름   몸무게   담당
0  홍길동  76.4  박현경
1  홍길동  75.7  김현경
2  홍길동  76.0  최현경
3  홍길동   NaN  최현경
4  홍길동  76.2  김현경
5  홍길동  75.7  최현경
6  홍길동   NaN  최현경
7  홍길동   NaN  김현경
8  홍길동  75.0  김현경

In [183]:
rawData.loc[0:3]

회차   이름         측정일   몸무게  단위   담당   지점
0   1  홍길동  2020-03-01  76.4  kg  박현경  관악구
1   2  홍길동  2020-03-02  75.7  kg  김현경  관악구
2   3  홍길동  2020-03-03  76.0  kg  최현경  여의도
3   4  홍길동  2020-03-04   NaN  kg  최현경  여의도

In [184]:
rawData[(rawData['지점']=='서초구') & (rawData['담당']=='김현경')]

회차   이름         측정일   몸무게  단위   담당   지점
7   8  홍길동  2020-03-08   NaN  kg  김현경  서초구
8   9  홍길동  2020-03-09  75.0  kg  김현경  서초구

In [185]:

        
rawData[ (rawData['지점'] == '서초구') & (rawData['담당'].isin(['김현경', '최현경'])) ]

회차   이름         측정일   몸무게  단위   담당   지점
5   6  홍길동  2020-03-06  75.7  kg  최현경  서초구
6   7  홍길동  2020-03-07   NaN  kg  최현경  서초구
7   8  홍길동  2020-03-08   NaN  kg  김현경  서초구
8   9  홍길동  2020-03-09  75.0  kg  김현경  서초구

In [186]:
rawData[(rawData['담당'].str.contains('김'))]

회차   이름         측정일   몸무게  단위   담당   지점
1   2  홍길동  2020-03-02  75.7  kg  김현경  관악구
4   5  홍길동  2020-03-05  76.2  kg  김현경  강남구
7   8  홍길동  2020-03-08   NaN  kg  김현경  서초구
8   9  홍길동  2020-03-09  75.0  kg  김현경  서초구

In [187]:
rawData[rawData['몸무게'].isna()]

회차   이름         측정일  몸무게  단위   담당   지점
3   4  홍길동  2020-03-04  NaN  kg  최현경  여의도
6   7  홍길동  2020-03-07  NaN  kg  최현경  서초구
7   8  홍길동  2020-03-08  NaN  kg  김현경  서초구

In [188]:
rawData[rawData['몸무게'].notna()]

회차   이름         측정일   몸무게  단위   담당   지점
0   1  홍길동  2020-03-01  76.4  kg  박현경  관악구
1   2  홍길동  2020-03-02  75.7  kg  김현경  관악구
2   3  홍길동  2020-03-03  76.0  kg  최현경  여의도
4   5  홍길동  2020-03-05  76.2  kg  김현경  강남구
5   6  홍길동  2020-03-06  75.7  kg  최현경  서초구
8   9  홍길동  2020-03-09  75.0  kg  김현경  서초구

In [189]:
rawData['몸무게'].describe()

count     6.000000
mean     75.833333
std       0.492612
min      75.000000
25%      75.700000
50%      75.850000
75%      76.150000
max      76.400000
Name: 몸무게, dtype: float64

In [190]:
rawData[rawData['몸무게'] > 76.15]

회차   이름         측정일   몸무게  단위   담당   지점
0   1  홍길동  2020-03-01  76.4  kg  박현경  관악구
4   5  홍길동  2020-03-05  76.2  kg  김현경  강남구

In [191]:
low=rawData['몸무게'].quantile(0.01)
high=rawData['몸무게'].quantile(0.99)
rawData[ (rawData['몸무게'] < high) & (rawData['몸무게'] > low) ]

회차   이름         측정일   몸무게  단위   담당   지점
1   2  홍길동  2020-03-02  75.7  kg  김현경  관악구
2   3  홍길동  2020-03-03  76.0  kg  최현경  여의도
4   5  홍길동  2020-03-05  76.2  kg  김현경  강남구
5   6  홍길동  2020-03-06  75.7  kg  최현경  서초구

In [192]:
rawData[rawData.duplicated(subset=['지점'],keep=False)]


회차   이름         측정일   몸무게  단위   담당   지점
0   1  홍길동  2020-03-01  76.4  kg  박현경  관악구
1   2  홍길동  2020-03-02  75.7  kg  김현경  관악구
2   3  홍길동  2020-03-03  76.0  kg  최현경  여의도
3   4  홍길동  2020-03-04   NaN  kg  최현경  여의도
5   6  홍길동  2020-03-06  75.7  kg  최현경  서초구
6   7  홍길동  2020-03-07   NaN  kg  최현경  서초구
7   8  홍길동  2020-03-08   NaN  kg  김현경  서초구
8   9  홍길동  2020-03-09  75.0  kg  김현경  서초구

In [193]:
pd.pivot_table(rawData,index='지점',values='몸무게')

몸무게
지점        
강남구  76.20
관악구  76.05
서초구  75.35
여의도  76.00

In [194]:
pd.pivot_table(rawData,index='지점',values='몸무게',aggfunc=np.sum)

몸무게
지점        
강남구   76.2
관악구  152.1
서초구  150.7
여의도   76.0

In [195]:
rawData.groupby(['지점'])

In [196]:
rawData.groupby(['지점'])['몸무게'].mean()


지점
강남구    76.20
관악구    76.05
서초구    75.35
여의도    76.00
Name: 몸무게, dtype: float64

In [197]:
rawData.groupby(['지점','담당'])[['몸무게']].mean()

몸무게
지점  담당       
강남구 김현경  76.2
관악구 김현경  75.7
    박현경  76.4
서초구 김현경  75.0
    최현경  75.7
여의도 최현경  76.0

In [198]:
rawData.loc[rawData['몸무게'] >= 76,'상태']='비만'

In [199]:
rawData

회차   이름         측정일   몸무게  단위   담당   지점   상태
0   1  홍길동  2020-03-01  76.4  kg  박현경  관악구   비만
1   2  홍길동  2020-03-02  75.7  kg  김현경  관악구  NaN
2   3  홍길동  2020-03-03  76.0  kg  최현경  여의도   비만
3   4  홍길동  2020-03-04   NaN  kg  최현경  여의도  NaN
4   5  홍길동  2020-03-05  76.2  kg  김현경  강남구   비만
5   6  홍길동  2020-03-06  75.7  kg  최현경  서초구  NaN
6   7  홍길동  2020-03-07   NaN  kg  최현경  서초구  NaN
7   8  홍길동  2020-03-08   NaN  kg  김현경  서초구  NaN
8   9  홍길동  2020-03-09  75.0  kg  김현경  서초구  NaN

In [200]:

rawData.loc[ rawData['몸무게'] < 76, '상태'] = '정상'

In [201]:
rawData

회차   이름         측정일   몸무게  단위   담당   지점   상태
0   1  홍길동  2020-03-01  76.4  kg  박현경  관악구   비만
1   2  홍길동  2020-03-02  75.7  kg  김현경  관악구   정상
2   3  홍길동  2020-03-03  76.0  kg  최현경  여의도   비만
3   4  홍길동  2020-03-04   NaN  kg  최현경  여의도  NaN
4   5  홍길동  2020-03-05  76.2  kg  김현경  강남구   비만
5   6  홍길동  2020-03-06  75.7  kg  최현경  서초구   정상
6   7  홍길동  2020-03-07   NaN  kg  최현경  서초구  NaN
7   8  홍길동  2020-03-08   NaN  kg  김현경  서초구  NaN
8   9  홍길동  2020-03-09  75.0  kg  김현경  서초구   정상

In [202]:
rawData['지역']='서울'

In [203]:
rawData.drop(columns='지역')

회차   이름         측정일   몸무게  단위   담당   지점   상태
0   1  홍길동  2020-03-01  76.4  kg  박현경  관악구   비만
1   2  홍길동  2020-03-02  75.7  kg  김현경  관악구   정상
2   3  홍길동  2020-03-03  76.0  kg  최현경  여의도   비만
3   4  홍길동  2020-03-04   NaN  kg  최현경  여의도  NaN
4   5  홍길동  2020-03-05  76.2  kg  김현경  강남구   비만
5   6  홍길동  2020-03-06  75.7  kg  최현경  서초구   정상
6   7  홍길동  2020-03-07   NaN  kg  최현경  서초구  NaN
7   8  홍길동  2020-03-08   NaN  kg  김현경  서초구  NaN
8   9  홍길동  2020-03-09  75.0  kg  김현경  서초구   정상

In [204]:
rawData

회차   이름         측정일   몸무게  단위   담당   지점   상태  지역
0   1  홍길동  2020-03-01  76.4  kg  박현경  관악구   비만  서울
1   2  홍길동  2020-03-02  75.7  kg  김현경  관악구   정상  서울
2   3  홍길동  2020-03-03  76.0  kg  최현경  여의도   비만  서울
3   4  홍길동  2020-03-04   NaN  kg  최현경  여의도  NaN  서울
4   5  홍길동  2020-03-05  76.2  kg  김현경  강남구   비만  서울
5   6  홍길동  2020-03-06  75.7  kg  최현경  서초구   정상  서울
6   7  홍길동  2020-03-07   NaN  kg  최현경  서초구  NaN  서울
7   8  홍길동  2020-03-08   NaN  kg  김현경  서초구  NaN  서울
8   9  홍길동  2020-03-09  75.0  kg  김현경  서초구   정상  서울

In [205]:
rawData.drop(columns='지역',inplace=True)

In [206]:
rawData

회차   이름         측정일   몸무게  단위   담당   지점   상태
0   1  홍길동  2020-03-01  76.4  kg  박현경  관악구   비만
1   2  홍길동  2020-03-02  75.7  kg  김현경  관악구   정상
2   3  홍길동  2020-03-03  76.0  kg  최현경  여의도   비만
3   4  홍길동  2020-03-04   NaN  kg  최현경  여의도  NaN
4   5  홍길동  2020-03-05  76.2  kg  김현경  강남구   비만
5   6  홍길동  2020-03-06  75.7  kg  최현경  서초구   정상
6   7  홍길동  2020-03-07   NaN  kg  최현경  서초구  NaN
7   8  홍길동  2020-03-08   NaN  kg  김현경  서초구  NaN
8   9  홍길동  2020-03-09  75.0  kg  김현경  서초구   정상

In [210]:
rawData.loc[9]=[10,'고은애','2020-03-10',80,'kg','이현경','강북구','비만']


In [211]:
rawData

회차   이름         측정일   몸무게  단위   담당   지점   상태
0   1  홍길동  2020-03-01  76.4  kg  박현경  관악구   비만
1   2  홍길동  2020-03-02  75.7  kg  김현경  관악구   정상
2   3  홍길동  2020-03-03  76.0  kg  최현경  여의도   비만
3   4  홍길동  2020-03-04   NaN  kg  최현경  여의도  NaN
4   5  홍길동  2020-03-05  76.2  kg  김현경  강남구   비만
5   6  홍길동  2020-03-06  75.7  kg  최현경  서초구   정상
6   7  홍길동  2020-03-07   NaN  kg  최현경  서초구  NaN
7   8  홍길동  2020-03-08   NaN  kg  김현경  서초구  NaN
8   9  홍길동  2020-03-09  75.0  kg  김현경  서초구   정상
9  10  고은애  2020-03-10  80.0  kg  이현경  강북구   비만